### PR TITLE
Vertical Input Props

### PR DESCRIPTION
**Pull request by ETLopes**
create props to change field input orientation from horizontal to vertical

### CODE REVIEW

**Comment by pavawit** [comment]
But https://github.com/sbycrosz/react-native-credit-card-input/pull/137

**Comment by ebellumat** [comment]
Please, bring your pull requests to my repo. I Will maintain this lib.

https://github.com/ebellumat/react-native-credit-card-input

**Comment by mateosilguero** [comment]
@ebellumat did you publish your package ?

**Comment by nikolajordanovski** [comment]
Any update on this?

**Pull request closed without merging**
