### PR TITLE
add support for verve card

### PR DESCRIPTION
**Pull request by nwaughachukwuma**
Hey @sbycrosz, I had made a new card addition (Verve) which is a well-known card in Africa and had published it under another npm repository [here](https://www.npmjs.com/package/react-native-credit-card-input-with-verve). But I feel it's better to integrate it with this one and pull that one down. Please explore and see if the addition aligns with your design pattern. Thanks

### CODE REVIEW

**Comment by ebellumat** [comment]
Please, bring your pull requests to my repo. I Will maintain this lib.

https://github.com/ebellumat/react-native-credit-card-input

**Comment by nwaughachukwuma** [comment]
Alright cool. I'll do so ASAP

**Comment by nwaughachukwuma** [comment]
I tried do this, but I could not find your repo. Is there something am not doing?

**Comment by ebellumat** [comment]
> I tried do this, but I could not find your repo. Is there something am not doing?

I don't know, can you try again? https://github.com/ebellumat/react-native-credit-card-input

**Comment by nwaughachukwuma** [comment]
Hi @ebellumat so I click on pull request on your repo and it takes me to @sbycrosz repo. See the link to the video below to for what transpired: 

https://photos.app.goo.gl/7NRCk96e9rvaTsQHA

**Comment by ebellumat** [comment]
> Hi @ebellumat so I click on pull request on your repo and it takes me to @sbycrosz repo. See the link to the video below to for what transpired:
> 
> https://photos.app.goo.gl/6NMCCRW6MKSzNemi9
> 
> https://photos.app.goo.gl/7NRCk96e9rvaTsQHA

First, fork my repo, after that, open the PR. =)

**Pull request closed without merging**
