### PR TITLE
Added compatibility for react 16

### PR DESCRIPTION
**Pull request by brunocascio**
Use `prop-types` external package instead of deprecated/removed `React.PropType`.

### CODE REVIEW

**Comment by IgorVanian** [comment]
Nice, just made a PR as well without seeing this one. Removing :)

**Comment by IgorVanian** [comment]
We need a commit here :/

**Comment by maitham1** [comment]
Any chance of a commit ??

**Comment by ujwal-setlur** [comment]
This is needed 👍

**Comment by sbycrosz** [comment]
Should be included in 4.1

**Pull request closed without merging**
